-- Import Data Huffadz 2015 from raw_data.tsv
-- Generated by script

INSERT INTO public.hafiz (
    nik, nama, tempat_lahir, tanggal_lahir, jenis_kelamin, 
    alamat, rt, rw, desa_kelurahan, kecamatan, kabupaten_kota, 
    telepon, sertifikat_tahfidz, mengajar, tmt_mengajar, 
    tahun_tes, periode_tes_id, status_kelulusan, 
    tempat_mengajar, keterangan, tanggal_lulus
) VALUES 
('3510211110760003', 'MOH. FATHUR ROHMAN', 'BANYUWANGI', '1976-10-11', 'L', 'LINGKUNGAN TANJUNG', '1', '2', 'KLATAK', 'KALIPURO', 'Kabupaten Banyuwangi', NULL, 'PPTQ LAWANG MALANG', true, '2007-10-28', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'lulus', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, '2021-01-01'),
('3510171211800002', 'SYAMSUL HADI', 'BANYUWANGI', '1980-11-12', 'L', 'JL. HAYAM WURUK NO. 67', '1', '4', 'PENATABAN', 'GIRI', 'Kabupaten Banyuwangi', NULL, 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', true, '2007-10-28', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, NULL),
('3510171010820002', 'MUSTAIN BILLAH', 'BANYUWANGI', '1982-10-10', 'L', 'JL. HAYAM WURUK', '3', '3', 'PENATABAN', 'GIRI', 'Kabupaten Banyuwangi', NULL, 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', true, '2001-01-11', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'lulus', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, '2015-01-01'),
('3510171212820002', 'MOHAMMAD HANIFI', 'BANYUWANGI', '1982-12-12', 'L', 'JL. INDRA GIRI', '2', '4', 'PENATABAN', 'GIRI', 'Kabupaten Banyuwangi', NULL, 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', true, '2011-09-15', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, NULL),
('3510176005820002', 'FAIQOTUL HIMA', 'BANYUWANGI', '1982-05-20', 'P', 'JL. INDRA GIRI', '2', '4', 'PENATABAN', 'GIRI', 'Kabupaten Banyuwangi', NULL, 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', true, '2011-09-15', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, NULL),
('3510175707840003', 'NURUL ULFA SYARIFAH', 'JEMBER', '1984-07-17', 'P', 'JL. INDRA GIRI NO. 47', '3', '6', 'PENATABAN', 'GIRI', 'Kabupaten Banyuwangi', NULL, 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', true, '2011-09-15', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'lulus', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, '2022-01-01'),
('3510171710880003', 'MOH. NURUL MUQORROBIN', 'BANYUWANGI', '1988-10-17', 'L', 'JL. HAYAM WURUK NO. 61', '3', '3', 'PENATABAN', 'GIRI', 'Kabupaten Banyuwangi', NULL, 'PP RIYADLUL QUR''AN NGASEM NGAJUM', true, '2011-09-15', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, NULL),
('3510172707870002', 'A. MUSLIM EFENDI', 'BANYUWANGI', '1987-07-27', 'L', 'JL. INDRA GIRI', '2', '4', 'PENATABAN', 'GIRI', 'Kabupaten Banyuwangi', NULL, 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', true, '2011-09-15', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, NULL),
('3504037110870001', 'LUK LUK NURIYANA', 'TULUNGAGUNG', '1987-10-31', 'P', 'JL. HAYAM WURUK', '3', '3', 'PENATABAN', 'GIRI', 'Kabupaten Banyuwangi', NULL, 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', true, '2001-01-11', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'MADRASATUL QUR''AN DARUL FURQON BANYUWANGI', NULL, NULL),
('3510090405830006', 'ACH. RODI HARTONO', 'JEMBER', '1983-05-04', 'L', 'Dsn. SUMBERWADUNG', '38', '15', 'KALIGONDO', 'GENTENG', 'Kabupaten Banyuwangi', NULL, 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', true, '2010-03-05', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'lulus', 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', NULL, '2022-01-01'),
('3510142601920002', 'MOH. ARIF IHSANI', 'BANYUWANGI', '1992-01-26', 'L', 'Dsn. KAMPUNG TENGAH', '1', '1', 'SUKOJATI', 'KABAT', 'Kabupaten Banyuwangi', NULL, 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', true, '2013-01-01', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', NULL, NULL),
('3510201311790001', 'SAIFUL', 'BANYUWANGI', '1979-11-13', 'L', 'Dsn. TUGUNG', '1', '2', 'SEMPU', 'SEMPU', 'Kabupaten Banyuwangi', NULL, 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', true, '2010-04-12', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', NULL, NULL),
('3510204410840004', 'SITI MU''AWANAH', 'BANYUWANGI', '1984-10-04', 'P', 'Dsn. TUGUNG', '1', '1', 'SEMPU', 'SEMPU', 'Kabupaten Banyuwangi', NULL, 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', true, '2009-02-01', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'lulus', 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', NULL, '2018-01-01'),
('3510204104940005', 'NILA MUSLIKHATUL AZIZAH', 'BANYUWANGI', '1994-04-01', 'P', 'Dsn. TUGUNG', '1', '1', 'SEMPU', 'SEMPU', 'Kabupaten Banyuwangi', NULL, 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', true, '2012-03-02', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'lulus', 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', NULL, '2023-01-01'),
('3510200804810007', 'SUHAIMI', 'BANYUWANGI', '1981-04-08', 'L', 'Dsn. TUGUNG', '1', '1', 'SEMPU', 'SEMPU', 'Kabupaten Banyuwangi', NULL, 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', true, '2008-02-05', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', NULL, NULL),
('840315331075', 'ALI IMRON', 'BANYUWANGI', '1975-11-02', 'L', 'Dsn. TUGUNG', '1', '1', 'SEMPU', 'SEMPU', 'Kabupaten Banyuwangi', NULL, 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', true, '2010-01-01', 2015, (SELECT id FROM public.periode_tes WHERE tahun = 2015 LIMIT 1), 'pending', 'PP TAHFIDZUL QUR''AN AL ABBAS AL AZHAR TUGUNG SEMPU BANYUWANGI', 'SIM', NULL)
ON CONFLICT (nik) DO UPDATE SET
    nama = EXCLUDED.nama,
    tempat_lahir = EXCLUDED.tempat_lahir,
    tanggal_lahir = EXCLUDED.tanggal_lahir,
    alamat = EXCLUDED.alamat,
    rt = EXCLUDED.rt,
    rw = EXCLUDED.rw,
    desa_kelurahan = EXCLUDED.desa_kelurahan,
    kecamatan = EXCLUDED.kecamatan,
    kabupaten_kota = EXCLUDED.kabupaten_kota,
    telepon = EXCLUDED.telepon,
    sertifikat_tahfidz = EXCLUDED.sertifikat_tahfidz,
    mengajar = EXCLUDED.mengajar,
    tmt_mengajar = EXCLUDED.tmt_mengajar,
    tempat_mengajar = EXCLUDED.tempat_mengajar,
    keterangan = EXCLUDED.keterangan,
    status_kelulusan = EXCLUDED.status_kelulusan,
    tanggal_lulus = EXCLUDED.tanggal_lulus,
    updated_at = NOW();
