-- Add keterangan column to hafiz table
ALTER TABLE public.hafiz ADD COLUMN IF NOT EXISTS keterangan TEXT;

-- Verify other columns exist or add them if missing based on user request
-- TAHUN SELEKSI -> tahun_tes (already exists)
-- DAERAH -> kabupaten_kota (already exists)
-- NIK -> nik (already exists)
-- NAMA -> nama (already exists)
-- TEMPAT LAHIR -> tempat_lahir (already exists)
-- TANGGAL LAHIR -> tanggal_lahir (already exists)
-- UMUR -> (derived from tanggal_lahir, no need to store unless requested, skipping for now to avoid redundancy)
-- JK -> jenis_kelamin (already exists)
-- ALAMAT -> alamat (already exists)
-- RT -> rt (already exists)
-- RW -> rw (already exists)
-- DESA/KELURAHAN -> desa_kelurahan (already exists)
-- KECAMATAN -> kecamatan (already exists)
-- KABUPATEN/KOTA -> kabupaten_kota (already exists)
-- SERTIFIKAT TAHFIDZ -> sertifikat_tahfidz (already exists)
-- MENGAJAR -> mengajar (already exists)
-- TMT MENGAJAR -> tmt_mengajar (already exists)
-- TELEPON -> telepon (already exists)
-- LULUS -> status_kelulusan (already exists)
