const fs = require('fs');
const path = require('path');

const inputFile = path.join(__dirname, '../database/raw_data.txt');
const outputFile = path.join(__dirname, '../database/02_import_huffadz_2015.sql');

const rawData = fs.readFileSync(inputFile, 'utf8');
const lines = rawData.split('\n');

const header = lines[0].split('\t');
// Mapping based on observation:
// 0: TAHUN SELEKSI (2015)
// 1: DAERAH
// 2: NIK
// 3: NAMA
// 4: TEMPAT LAHIR
// 5: TANGGAL LAHIR
// 6: UMUR
// 7: JK
// 8: ALAMAT
// 9: RT
// 10: RW
// 11: DESA/KELURAHAN
// 12: KECAMATAN
// 13: KABUPATEN/KOTA (Ignore)
// 14: SERTIFIKAT TAHFIDZ
// 15: MENGAJAR (Tempat Mengajar)
// 16: TMT MENGAJAR
// 17: TELEPON
// 18: KETERANGAN
// 19: LULUS

function parseDate(dateStr) {
    if (!dateStr || dateStr.trim() === '') return null;
    const parts = dateStr.split('/');
    if (parts.length === 3) {
        // DD/MM/YYYY
        return `${parts[2]}-${parts[1]}-${parts[0]}`;
    }
    return null;
}

function escapeSql(str) {
    if (!str) return 'NULL';
    return `'${str.replace(/'/g, "''").trim()}'`;
}

let sql = `-- Import Data Huffadz 2015 from raw_data.tsv
-- Generated by script

`;

const records = [];

for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    
    const cols = line.split('\t');
    if (cols.length < 5) continue; // Skip invalid lines

    try {
        const tahunTes = parseInt(cols[0]) || 2015;
        const daerah = cols[1];
        const nik = cols[2];
        const nama = cols[3];
        const tempatLahir = cols[4];
        const tanggalLahir = parseDate(cols[5]);
        const jk = cols[7]; // L/P
        const alamat = cols[8];
        const rt = cols[9];
        const rw = cols[10];
        const desa = cols[11];
        const kecamatan = cols[12];
        // col[13] KABUPATEN/KOTA - redundant
        const sertifikat = cols[14];
        const tempatMengajar = cols[15];
        const isMengajar = !!(tempatMengajar && tempatMengajar.trim().length > 0 && tempatMengajar !== '-' && tempatMengajar !== '??');
        const tmtMengajar = parseDate(cols[16]);
        const telepon = cols[17];
        const keterangan = cols[18]; // e.g. SIM
        const lulusStr = cols[19] || '';
        
        let statusKelulusan = 'pending';
        let tanggalLulus = null;
        
        // Logic for graduation
        if (lulusStr.trim().match(/^\d{4}$/)) {
            statusKelulusan = 'lulus';
            tanggalLulus = `${lulusStr.trim()}-01-01`;
        }

        if (!nik) continue;

        // Construct Value tuple
        const fields = [
            escapeSql(nik),
            escapeSql(nama),
            escapeSql(tempatLahir),
            tanggalLahir ? `'${tanggalLahir}'` : 'NULL',
            escapeSql(jk),
            escapeSql(alamat),
            escapeSql(rt),
            escapeSql(rw),
            escapeSql(desa),
            escapeSql(kecamatan),
            escapeSql(daerah), // kabupaten_kota
            escapeSql(telepon),
            escapeSql(sertifikat),
            isMengajar ? 'true' : 'false',
            tmtMengajar ? `'${tmtMengajar}'` : 'NULL',
            tahunTes,
            `(SELECT id FROM public.periode_tes WHERE tahun = ${tahunTes} LIMIT 1)`,
            `'${statusKelulusan}'`,
            escapeSql(tempatMengajar),
            escapeSql(keterangan),
            tanggalLulus ? `'${tanggalLulus}'` : 'NULL'
        ];

        records.push(`(${fields.join(', ')})`);
    } catch (e) {
        console.error(`Error parsing line ${i}: ${e.message}`);
    }
}

if (records.length > 0) {
    sql += `INSERT INTO public.hafiz (
    nik, nama, tempat_lahir, tanggal_lahir, jenis_kelamin, 
    alamat, rt, rw, desa_kelurahan, kecamatan, kabupaten_kota, 
    telepon, sertifikat_tahfidz, mengajar, tmt_mengajar, 
    tahun_tes, periode_tes_id, status_kelulusan, 
    tempat_mengajar, keterangan, tanggal_lulus
) VALUES 
${records.join(',\n')}
ON CONFLICT (nik) DO UPDATE SET
    nama = EXCLUDED.nama,
    tempat_lahir = EXCLUDED.tempat_lahir,
    tanggal_lahir = EXCLUDED.tanggal_lahir,
    alamat = EXCLUDED.alamat,
    rt = EXCLUDED.rt,
    rw = EXCLUDED.rw,
    desa_kelurahan = EXCLUDED.desa_kelurahan,
    kecamatan = EXCLUDED.kecamatan,
    kabupaten_kota = EXCLUDED.kabupaten_kota,
    telepon = EXCLUDED.telepon,
    sertifikat_tahfidz = EXCLUDED.sertifikat_tahfidz,
    mengajar = EXCLUDED.mengajar,
    tmt_mengajar = EXCLUDED.tmt_mengajar,
    tempat_mengajar = EXCLUDED.tempat_mengajar,
    keterangan = EXCLUDED.keterangan,
    status_kelulusan = EXCLUDED.status_kelulusan,
    tanggal_lulus = EXCLUDED.tanggal_lulus,
    updated_at = NOW();
`;
} else {
    sql += "-- No records found to insert";
}

fs.writeFileSync(outputFile, sql);
console.log(`Generated SQL for ${records.length} records to ${outputFile}`);
